[connections.internship_RLO]
dialect = "mysql"
driver = "pymysql"
host = "gondola.proxy.rlwy.net"
port = 10984
database = "railway"
username = "root"
password = "ryCwQZhvjpaKoBbNjDOsRUaqrfAcNWay"

[connections.ADOMobile]
spreadsheet = "https://docs.google.com/spreadsheets/d/1NFa5OkmqZw9DWMpLt30llHXYQYQ5hVFXjFDIqWo1nz4/edit?gid=1475101649#gid=1475101649"
#spreadsheet = "https://docs.google.com/spreadsheets/d/1CHgGiHOUPRLV-NLlQJjUUKPClfUNPstIqrBtWg_NcFI/edit?gid=1045613879#gid=1045613879"

[connections.MarketCompetition]
spreadsheet = "https://docs.google.com/spreadsheets/d/1NFa5OkmqZw9DWMpLt30llHXYQYQ5hVFXjFDIqWo1nz4/edit?gid=1475101649#gid=1475101649"
#spreadsheet = "https://docs.google.com/spreadsheets/d/1CHgGiHOUPRLV-NLlQJjUUKPClfUNPstIqrBtWg_NcFI/edit?gid=1045613879#gid=1045613879"

[connections.ADOIH]
spreadsheet = "https://docs.google.com/spreadsheets/d/1NFa5OkmqZw9DWMpLt30llHXYQYQ5hVFXjFDIqWo1nz4/edit?gid=72652241#gid=72652241"
#spreadsheet = "https://docs.google.com/spreadsheets/d/1CHgGiHOUPRLV-NLlQJjUUKPClfUNPstIqrBtWg_NcFI/edit?gid=422373884#gid=422373884"

[auth]
redirect_uri = "https://marketanalyst.streamlit.app" # Ngga Usah Diganti
cookie_secret = "0c9b308e8d55954161e6e3fe7b72d875b4fcb4790969d9502aed891b205c03cf"

[auth.google]
client_id = "232838743542-v3mmjiub4hcia7bhve2g2k5bpaca8ltb.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration" # Ngga Usah Diganti
